// Component Library registry (2026-10-01) — every widget on the site, which pages it is on, how
// it is built, and every variation the library shows. The library page (index.html) draws itself
// from this list; each variation is the REAL widget, loaded from the page named in `page` and
// isolated by _shared/component-mode.js — nothing here is a copy of a widget's markup.
//
// RULE: change a widget here first (check every variation in the library), then update every
// page in its `usedOn` list and compare them with "Compare across pages".
//
// Fields
//   id       anchor (#id) and share link (?only=id) — never rename once shared
//   build    'shared'  rendered by one shared function, so every page updates together
//            'copied'  hand-written markup repeated in each page — update every usedOn page
//            'mixed'   a copied shell that shared JS fills in (update the shell on every page)
//   source   where the code lives
//   usedOn   template folders (from a crawl of every page, 2026-10-01)
//   variants one row each: { label, page, sel, ls, cart, order, do, keep, q, h, sizes }
//            ls    storage seeded for that frame only (see S below)
//            do    actions after load (component-mode.js): click:, focus:, type:, addclass:, call:
//            keep  extra selector kept visible (dropdowns outside the widget)
//            q     extra query string for the page (e.g. 'q=snorkel', 'store=moorebank')
//            h     fixed frame height (drawers and overlays)
//            selM  a different selector for the mobile frame (when mobile uses another element)
//            sizes ['d','m'] (default both): d = 1280px desktop, m = 390px mobile

const PDP5 = ['vehicle-specific', 'config-variant', 'sibling-color', 'simple', 'grouped-bundle'];
const PLP3 = ['plp-camping', 'plp', 'vplp'];
const ALL_PAGES = ['home', 'store', 'store-finder', 'fit-my-vehicle', 'installation', 'cart', 'checkout', 'order-confirmation', ...PDP5, 'vehicle-category-landing', 'vlp', ...PLP3, 'brand', 'brands', 'search-results', 'header'];
const NOT_CHECKOUT = ALL_PAGES.filter(p => p !== 'checkout');

// Storage presets — merged into a variant's `ls`.
const S = {
  guest: { rrgSessionLoggedIn: 'false' },
  noVehicle: { rrgSessionVehicle: 'none' },
  ranger: { rrgSessionVehicle: 'ranger' },
  noStore: { rrgSessionStoreSet: 'false' },
  phase2: { rrgBuildPhase: '2' },
  nz: { rrgRegion: 'NZ' },
  uk: { rrgRegion: 'UK' },
  dark: { rrgVehicleFinderStyle: 'dark' },
  sale: { rrgSaleOn: 'true' },
  noComingSoon: { rrgShowComingSoonStores: 'false' },
};
// A template's Demo State choices, as the Demo State panel saves them.
const demo = (template, state) => ({ ['rrgDemo:' + template]: JSON.stringify(state) });
const v = (label, page, sel, opts = {}) => ({ label, page, sel, ...opts });

const RRG_GROUPS = [
  { id: 'global', title: 'Global: header, footer, drawers' },
  { id: 'product', title: 'Product page' },
  { id: 'listing', title: 'Listing, search & category' },
  { id: 'cart', title: 'Cart & checkout' },
  { id: 'stores', title: 'Stores, vehicles & brands' },
  { id: 'content', title: 'Home & content blocks' },
  { id: 'blocks', title: 'Building blocks' },
];

const RRG_COMPONENTS = [
  // ---------------------------------------------------------------- Global
  { id: 'campaign-strip', group: 'global', name: 'Sale Campaign Strip + Countdown', build: 'shared', usedOn: NOT_CHECKOUT,
    source: 'rrgCampaignStripHTML (campaign.js), drawn by rrgWidgetHeaderHTML (widgets.js); campaign.css. Only while Site Admin → Sale on (AU/NZ)',
    variants: [
      v('Sale on (Rack Friday)', 'header', '.campaign-strip', { ls: S.sale }),
    ] },
  { id: 'utility-bar', group: 'global', name: 'Utility Bar', build: 'shared', usedOn: NOT_CHECKOUT,
    source: 'rrgWidgetUtilityBarHTML (widgets.js); filled by applyRegion + rrgApplySessionState (shared.js, session-state.js)',
    variants: [
      v('AU — logged in, vehicle + store set', 'header', '.rrg-utility-bar'),
      v('Guest, no vehicle, no store', 'header', '.rrg-utility-bar', { ls: { ...S.guest, ...S.noVehicle, ...S.noStore } }),
      v('NZ', 'header', '.rrg-utility-bar', { ls: S.nz }),
      v('UK', 'header', '.rrg-utility-bar', { ls: S.uk }),
      v('Sale on (Rack Friday)', 'header', '.rrg-utility-bar', { ls: S.sale }),
    ] },
  { id: 'region-selector', group: 'global', name: 'Region Selector', build: 'shared', usedOn: NOT_CHECKOUT,
    source: 'Menu in rrgWidgetUtilityBarHTML (widgets.js); initRegionSwitcher (shared.js)',
    variants: [
      v('Open', 'header', '.rrg-utility-bar', { do: 'click:.region-switcher-toggle', sizes: ['d'], keep: '.region-switcher-menu' }),
    ] },
  { id: 'main-header', group: 'global', name: 'Main Header & Nav', build: 'shared', usedOn: NOT_CHECKOUT,
    source: 'rrgWidgetMainHeaderHTML, inside .rrg-header-shell from rrgWidgetHeaderHTML (widgets.js); cart badge from cart.js',
    variants: [
      v('AU', 'header', '.rrg-header-shell'),
      v('UK skin', 'header', '.rrg-header-shell', { ls: S.uk }),
      v('With items in the cart', 'header', '.rrg-header-shell', { cart: 'full' }),
      v('Sale on (Rack Friday) — nav sale link', 'header', '.rrg-header-shell', { ls: S.sale, sizes: ['d'] }),
    ] },
  { id: 'mega-menu', group: 'global', name: 'Mega Menu (desktop)', build: 'shared', usedOn: NOT_CHECKOUT,
    source: 'Shell in rrgWidgetMainHeaderHTML (widgets.js); buildMegaMenuDesktop + mmPromoTileHTML (mega-menu.js)',
    variants: [
      v('Open, sale on (Rack Friday banner)', 'header', '.rrg-header-shell', { do: 'click:.mega-menu-toggle', ls: S.sale, sizes: ['d'], h: 760 }),
      v('Open, no sale (Store Finder banner)', 'header', '.rrg-header-shell', { do: 'click:.mega-menu-toggle', sizes: ['d'], h: 760 }),
    ] },
  { id: 'search-typeahead', group: 'global', name: 'Header Search & Typeahead', build: 'shared', usedOn: NOT_CHECKOUT,
    source: 'Search box in rrgWidgetMainHeaderHTML (widgets.js); headerSearchFocusHTML / headerSearchTypingHTML (shared.js)',
    variants: [
      v('Focused (recent + popular + suggested products)', 'header', '.rrg-header-shell', { do: 'focus:.rrg-main-header .rrg-search input', keep: '.rrg-search-suggest', sizes: ['d'] }),
      v('Typing "roof"', 'header', '.rrg-header-shell', { do: 'type:.rrg-main-header .rrg-search input|roof', keep: '.rrg-search-suggest', sizes: ['d'] }),
    ] },
  { id: 'sticky-header', group: 'global', name: 'Sticky Mobile Header', build: 'shared', usedOn: NOT_CHECKOUT,
    source: 'rrgWidgetStickyHeaderHTML (widgets.js); initPersistentBar shows it on scroll (shared.js)',
    variants: [v('Shown after scrolling', 'header', '.rrg-sticky-header', { do: 'addclass:.rrg-sticky-header|visible', sizes: ['m'] })] },
  { id: 'mobile-menu', group: 'global', name: 'Mobile Menu Takeover', build: 'shared', usedOn: NOT_CHECKOUT,
    source: 'Shell: rrgWidgetMobileTakeoverHTML (widgets.js); buildMegaMenuMobile (mega-menu.js)',
    variants: [
      v('Open', 'header', '.mm-mobile-takeover', { do: 'click:.rrg-main-header .mobile-nav-toggle', sizes: ['m'], h: 780 }),
      v('Guest', 'header', '.mm-mobile-takeover', { do: 'click:.rrg-main-header .mobile-nav-toggle', ls: S.guest, sizes: ['m'], h: 780 }),
    ] },
  { id: 'breadcrumbs', group: 'global', name: 'Breadcrumbs', build: 'mixed', usedOn: ['store', 'store-finder', 'fit-my-vehicle', 'installation', 'cart', ...PDP5, 'vehicle-category-landing', 'vlp', ...PLP3, 'brand', 'brands', 'search-results'],
    source: 'Static on most pages; plpRenderBreadcrumb (plp.js) on listing pages',
    variants: [
      v('Product page', 'simple', '.rrg-crumbs'),
      v('Listing page', 'plp', '.rrg-crumbs'),
    ] },
  { id: 'breadcrumb-row', group: 'global', name: 'Breadcrumb Row + Change Vehicle', build: 'mixed', usedOn: ['store', 'store-finder', 'fit-my-vehicle', 'installation', 'cart', 'vehicle-category-landing', 'vlp', ...PLP3, 'brand', 'brands', 'search-results'],
    source: 'Static row; plpRenderBreadcrumb (plp.js), vlpRenderHeader (vlp)',
    variants: [
      v('VLP (with Change Vehicle)', 'vlp', '.plp-crumbs-row'),
      v('PLP', 'plp', '.plp-crumbs-row'),
      v('Store Finder', 'store-finder', '.plp-crumbs-row'),
    ] },
  { id: 'footer', group: 'global', name: 'Footer', build: 'shared', usedOn: NOT_CHECKOUT,
    source: 'rrgWidgetFooterHTML (widgets.js); renderFooterSocial / renderFooterPayments / applyRegionFooter (shared.js)',
    variants: [
      v('AU', 'header', '.rrg-footer'),
      v('NZ', 'header', '.rrg-footer', { ls: S.nz }),
      v('UK', 'header', '.rrg-footer', { ls: S.uk }),
      v('Sale on (Rack Friday)', 'header', '.rrg-footer', { ls: S.sale }),
    ] },
  { id: 'mini-cart', group: 'global', name: 'Mini-cart Drawer', build: 'shared', usedOn: ALL_PAGES.filter(p => !['vlp', 'checkout'].includes(p)),
    source: 'rrgBuildMiniCart / rrgRenderMiniCart (cart.js)',
    variants: [
      v('Items in the cart', 'header', '.mini-cart-backdrop', { cart: 'full', do: 'call:rrgOpenMiniCart', h: 760 }),
      v('Just added', 'header', '.mini-cart-backdrop', { cart: 'accessories', do: 'call:rrgOpenMiniCart|true', h: 760 }),
      v('Empty', 'header', '.mini-cart-backdrop', { do: 'call:rrgOpenMiniCart', h: 520 }),
    ] },
  { id: 'fit-finder-drawer', group: 'global', name: 'Fit Finder Drawer', build: 'shared', usedOn: NOT_CHECKOUT,
    source: 'buildFitFinderDrawer / openFitFinderDrawer (shared.js), holding rrgWidgetVehicleFinderHTML (widgets.js) — always the no-vehicle cascade',
    variants: [
      v('Light', 'header', '.fit-finder-drawer-backdrop', { do: 'call:openFitFinderDrawer|navigate', h: 760 }),
      v('Dark', 'header', '.fit-finder-drawer-backdrop', { ls: S.dark, do: 'call:openFitFinderDrawer|navigate', h: 760 }),
    ] },

  // ---------------------------------------------------------------- Product page
  { id: 'decision-panel', group: 'product', name: 'Decision Panel (whole)', build: 'copied', usedOn: [...PDP5, 'store'],
    source: 'Static per page; applyStockStatus / applyCartConflict / syncSaleTag (shared.js) change it',
    note: 'The full right-hand column. Its parts are also listed one by one below.',
    variants: [
      v('Simple — default', 'simple', '.decision-panel'),
      v('Vehicle-Specific — fits', 'vehicle-specific', '.decision-panel'),
      v('Config-Variant', 'config-variant', '.decision-panel'),
      v('Sibling / Colour', 'sibling-color', '.decision-panel'),
      v('Grouped / Bundle', 'grouped-bundle', '.decision-panel'),
    ] },
  { id: 'stock-status', group: 'product', name: 'Stock Status (price, stock line, Add to Cart)', build: 'shared', usedOn: PDP5,
    source: 'applyStockStatus / renderStockLine (shared.js), STOCK_STATUS',
    variants: ['in_stock', 'low_stock', 'out_of_stock', 'special_order', 'discontinued'].map(s =>
      v({ in_stock: 'In Stock', low_stock: 'Low Stock', out_of_stock: 'Out of Stock', special_order: 'Special Order', discontinued: 'Discontinued' }[s], 'simple', '.decision-panel', { ls: demo('simple', { 'r:stockStatus': s }), sizes: ['d'] }))
      .concat([v('Phase 2 — stock at your store', 'simple', '.decision-panel', { ls: { ...S.phase2, ...demo('simple', { 'r:storeStock': 'nearby' }) }, sizes: ['d'] })]) },
  { id: 'cart-conflict', group: 'product', name: 'Cart Conflict Banner', build: 'shared', usedOn: PDP5,
    source: 'applyCartConflict (shared.js)',
    variants: [
      v('Compatible item in cart', 'vehicle-specific', '.decision-panel', { ls: demo('vehicle-specific', { 'r:cartConflict': 'compatible' }), sizes: ['d'] }),
      v('Incompatible item in cart', 'vehicle-specific', '.decision-panel', { ls: demo('vehicle-specific', { 'r:cartConflict': 'incompatible' }), sizes: ['d'] }),
    ] },
  { id: 'product-gallery', group: 'product', name: 'Product Gallery', build: 'mixed', usedOn: [...PDP5, 'store'],
    source: 'Static per page; initGalleryCarousels / applyVideoFlag (shared.js)',
    variants: [
      v('Simple', 'simple', '.gallery-col', { selM: '.gallery-main' }),
      v('Vehicle-Specific', 'vehicle-specific', '.gallery-col', { selM: '.gallery-main' }),
      v('No video', 'simple', '.gallery-col', { selM: '.gallery-main', ls: demo('simple', { 'c:video': false }) }),
      v('Store page (store photos)', 'store', '.gallery-col', { selM: '.gallery-main' }),
    ] },
  { id: 'sku-row', group: 'product', name: 'Brand Logo + SKU', build: 'copied', usedOn: PDP5,
    source: 'Static per page; initCopyButtons (shared.js)',
    variants: [v('Default', 'simple', '.decision-panel-top')] },
  { id: 'short-desc', group: 'product', name: 'Short Description + Read more', build: 'mixed', usedOn: PDP5,
    source: 'Static per page; layoutShortDesc (shared.js)',
    variants: [v('Default', 'simple', '.short-desc')] },
  { id: 'reviews-strip', group: 'product', name: 'Reviews Strip', build: 'mixed', usedOn: PDP5,
    source: 'Static per page; initReviewSummary (shared.js) — live rating from reviews.io',
    note: 'Hidden when the product has no reviews yet (e.g. Simple).',
    variants: [v('With reviews', 'vehicle-specific', '.reviews-strip')] },
  { id: 'fitment-status', group: 'product', name: 'Fitment Status', build: 'shared', usedOn: ['vehicle-specific'],
    source: 'renderFitmentHTML / applyFitmentState (shared.js)',
    variants: [
      v('Fits your vehicle', 'vehicle-specific', '.fitment[data-fitment-slot]'),
      v('Doesn\'t fit (Ford Ranger)', 'vehicle-specific', '.fitment[data-fitment-slot]', { ls: S.ranger }),
      v('No vehicle set', 'vehicle-specific', '.fitment[data-fitment-slot]', { ls: S.noVehicle }),
    ] },
  { id: 'vehicle-fit-notes', group: 'product', name: 'Vehicle Fit Notes', build: 'copied', usedOn: ['vehicle-specific'],
    source: 'Static; applyVehicleFitNotesFlag (shared.js)',
    variants: [v('Shown', 'vehicle-specific', '#vehicleFitNotes', { ls: demo('vehicle-specific', { 'c:vehicleFitNotes': true }) })] },
  { id: 'variant-picker', group: 'product', name: 'Variant Picker (+ Get It Fitted)', build: 'copied', usedOn: ['config-variant', 'vehicle-specific'],
    source: 'Inline per page (renderVariantPicker / renderVehicleVariantPicker); buildFittedCard (shared.js)',
    variants: [
      v('Config-Variant', 'config-variant', '.variant-picker'),
      v('Vehicle-Specific', 'vehicle-specific', '.variant-picker'),
      v('Get It Fitted as a 3rd card', 'config-variant', '.variant-picker', { ls: demo('config-variant', { 'r:fittedMode': 'card' }) }),
      v('Get It Fitted as a checkbox', 'config-variant', '.cta-col', { ls: demo('config-variant', { 'r:fittedMode': 'checkbox' }) }),
    ] },
  { id: 'swatch-grid', group: 'product', name: 'Colour Swatch Grid', build: 'copied', usedOn: ['sibling-color'],
    source: 'Inline in sibling-color',
    variants: [v('Default', 'sibling-color', '.swatch-grid')] },
  { id: 'price-block', group: 'product', name: 'Price Block + Sale Tag', build: 'mixed', usedOn: PDP5,
    source: 'Static per page; syncSaleTag (shared.js)',
    variants: [
      v('On sale, no sale event (no tag)', 'simple', '.price-block'),
      v('On sale, Rack Friday on (tag)', 'simple', '.price-block', { ls: S.sale }),
      v('Not on sale', 'simple', '.price-block', { ls: demo('simple', { 'c:sale': false }) }),
      v('NZ', 'simple', '.price-block', { ls: S.nz }),
      v('UK', 'simple', '.price-block', { ls: S.uk }),
    ] },
  { id: 'add-to-cart', group: 'product', name: 'Add to Cart + Payment Badges', build: 'mixed', usedOn: PDP5,
    source: 'Static per page; paymentBadgeSet (shared.js)',
    variants: [
      v('AU', 'simple', '.cta-col'),
      v('NZ', 'simple', '.cta-col', { ls: S.nz }),
      v('UK', 'simple', '.cta-col', { ls: S.uk }),
      v('Sale on (Rack Friday)', 'simple', '.cta-col', { ls: S.sale }),
    ] },
  { id: 'exdemo', group: 'product', name: 'Ex-Demo / B-Stock Link + Drawer', build: 'shared', usedOn: PDP5,
    source: 'applyExdemoFlag / buildExdemoSlideout (shared.js)',
    variants: [
      v('Link under the price', 'simple', '.decision-panel', { ls: demo('simple', { 'c:exdemo': true }), sizes: ['d'] }),
      v('Drawer open', 'simple', '.exdemo-slideout-backdrop', { ls: demo('simple', { 'c:exdemo': true }), do: 'click:.exdemo-inline-link', h: 760 }),
    ] },
  { id: 'delivery-collect', group: 'product', name: 'Delivery / Click & Collect', build: 'mixed', usedOn: PDP5,
    source: 'Static per page (copies differ); initDeliveryCollectTabs / initDcPostcode (shared.js)',
    variants: [
      v('Click & Collect (AU default)', 'simple', '.dc-widget'),
      v('Delivery tab', 'simple', '.dc-widget', { do: 'click:.dc-tabs button:nth-child(1)' }),
      v('Delivery unavailable', 'simple', '.dc-widget', { ls: demo('simple', { 'c:shipping': false }) }),
      v('UK', 'simple', '.dc-widget', { ls: S.uk }),
    ] },
  { id: 'store-slideout', group: 'product', name: 'Store Slide-out + Stock Pills', build: 'shared', usedOn: [...PDP5, 'home', 'vlp', ...PLP3, 'brand', 'search-results'],
    source: 'buildStoreSlideout / rrgStorePillsHTML (shared.js)',
    variants: [
      v('Open', 'simple', '#storeSlideoutBackdrop', { do: 'call:openStoreSlideout', h: 760 }),
      v('Open — Phase 2', 'simple', '#storeSlideoutBackdrop', { ls: S.phase2, do: 'call:openStoreSlideout', h: 760 }),
    ] },
  { id: 'package-contents', group: 'product', name: 'What\'s Included (Package Contents)', build: 'copied', usedOn: ['vehicle-specific', 'grouped-bundle'],
    source: 'Static per page',
    variants: [
      v('Vehicle-Specific', 'vehicle-specific', '.package-items'),
      v('Grouped / Bundle', 'grouped-bundle', '.package-items'),
    ] },
  { id: 'install-cta', group: 'product', name: 'Get It Installed', build: 'copied', usedOn: PDP5,
    source: 'Static per page; copy changes with the Fitment Gallery count (shared.js)',
    variants: [
      v('Simple', 'simple', '.install-cta-panel'),
      v('Vehicle-Specific (with fitments)', 'vehicle-specific', '.install-cta-panel'),
      v('Vehicle-Specific (no fitments)', 'vehicle-specific', '.install-cta-panel', { ls: demo('vehicle-specific', { 'c:fitGallery': false }) }),
    ] },
  { id: 'product-tabs', group: 'product', name: 'Description & Specs', build: 'copied', usedOn: PDP5,
    source: 'Static per page',
    variants: [v('Simple', 'simple', '.body-cols'), v('Vehicle-Specific', 'vehicle-specific', '.body-cols')] },
  { id: 'showroom-finder', group: 'product', name: 'Showroom Finder + Map', build: 'mixed', usedOn: PDP5,
    source: 'Static per page (copies differ); applyShowroomFlag / applyShowroomMapFlag (shared.js)',
    note: 'When the product is not on display anywhere, the whole section is hidden.',
    variants: [
      v('On display (AU)', 'simple', '.showroom-widget'),
      v('NZ', 'simple', '.showroom-widget', { ls: S.nz }),
    ] },
  { id: 'related-products', group: 'product', name: 'Related Products', build: 'copied', usedOn: [...PDP5, ...PLP3],
    source: 'Static, hand-written cards',
    variants: [v('Product page', 'simple', '.related-section'), v('Listing page', 'plp', '.related-section')] },
  { id: 'sticky-mobile-cta', group: 'product', name: 'Sticky Mobile Add to Cart', build: 'copied', usedOn: PDP5,
    source: 'Static per page; initStickyCta (shared.js)',
    variants: [
      v('Simple', 'simple', '.sticky-cta-mobile', { do: 'addclass:.sticky-cta-mobile|visible', sizes: ['m'] }),
      v('Vehicle-Specific (with thumbnail)', 'vehicle-specific', '.sticky-cta-mobile', { do: 'addclass:.sticky-cta-mobile|visible', sizes: ['m'] }),
    ] },
  { id: 'persistent-bar', group: 'product', name: 'Persistent Bar (desktop)', build: 'copied', usedOn: PDP5,
    source: 'Static per page; initPersistentBar (shared.js)',
    variants: [
      v('Simple', 'simple', '.persistent-bar', { do: 'addclass:.persistent-bar|visible', sizes: ['d'], h: 120 }),
      v('Vehicle-Specific', 'vehicle-specific', '.persistent-bar', { do: 'addclass:.persistent-bar|visible', sizes: ['d'], h: 120 }),
    ] },

  // ---------------------------------------------------------------- Listing, search & category
  { id: 'category-hero', group: 'listing', name: 'Category Hero', build: 'mixed', usedOn: ['vehicle-category-landing', 'vlp', ...PLP3],
    source: 'Static (both states in the page); plpRenderHero / applyPlpHeroImageFlag (plp.js)',
    variants: [
      v('PLP — vehicle set', 'plp', '#plpHeroVehicleSet'),
      v('PLP — category image', 'plp', '#plpHeroVehicleSet', { ls: demo('plp', { 'r:plpHeroImage': 'category' }) }),
      v('PLP — no vehicle', 'plp', '.plp-hero:not(#plpHeroVehicleSet)', { ls: S.noVehicle }),
      v('VPLP', 'vplp', '.plp-hero'),
      v('VCLP', 'vehicle-category-landing', '.plp-hero'),
      v('VLP', 'vlp', '#vlpHero'),
    ] },
  { id: 'shop-by', group: 'listing', name: 'Shop By Row', build: 'shared', usedOn: [...PLP3, 'search-results'],
    source: 'plpRenderShopBy (plp.js)',
    variants: [v('PLP Bike Racks', 'plp', '.plp-shopby'), v('PLP Camping', 'plp-camping', '.plp-shopby'), v('Search category tabs', 'search-results', '.plp-shopby')] },
  { id: 'listing-toolbar', group: 'listing', name: 'Listing Toolbar', build: 'copied', usedOn: [...PLP3, 'brand', 'search-results'],
    source: 'Static per page; wired by plp.js',
    variants: [v('PLP', 'plp', '.plp-toolbar'), v('Search', 'search-results', '.plp-toolbar')] },
  { id: 'filter-sidebar', group: 'listing', name: 'Filter Sidebar + Merch', build: 'shared', usedOn: [...PLP3, 'brand', 'search-results'],
    source: 'plpFilterGroupHTML + merch sidebar (plp.js)',
    variants: [v('PLP Bike Racks', 'plp', '.plp-sidebar', { sizes: ['d'] }), v('PLP Camping', 'plp-camping', '.plp-sidebar', { sizes: ['d'] })] },
  { id: 'filter-drawer', group: 'listing', name: 'Filter Drawer (mobile)', build: 'shared', usedOn: [...PLP3, 'brand', 'search-results'],
    source: 'plp.js filter slide-out',
    variants: [v('Open', 'plp', '.plp-filter-slideout-backdrop', { do: 'click:#plpRefineBtn', sizes: ['m'], h: 780 })] },
  { id: 'product-card', group: 'listing', name: 'Product Card', build: 'shared', usedOn: ['home', 'store', 'cart', 'vlp', ...PLP3, 'brand', 'search-results'],
    source: 'plpCardHTML / plpListCardHTML / plpStockLineHTML / plpFitStatusHTML (plp.js)',
    variants: [
      v('Grid card', 'plp', '.plp-card'),
      v('Grid card — fitment chip', 'vplp', '.plp-card'),
      v('Phase 2 — ribbons + compare', 'plp', '.plp-card', { ls: { ...S.phase2, ...demo('plp', { 'c:plpRibbons': true, 'c:plpCompare': true }) } }),
      v('Sale on (Rack Friday) — campaign tag', 'plp', '.plp-card', { ls: S.sale }),
    ] },
  { id: 'results-grid', group: 'listing', name: 'Results Grid / List', build: 'shared', usedOn: [...PLP3, 'brand', 'search-results'],
    source: 'plpCardHTML / plpListCardHTML (plp.js)',
    variants: [
      v('Grid', 'plp', '#plpResults'),
      v('List view', 'plp', '#plpResults', { do: 'click:#plpViewList', sizes: ['d'] }),
      v('VPLP (fitment-locked)', 'vplp', '#plpResults'),
    ] },
  { id: 'pagination', group: 'listing', name: 'Pagination', build: 'shared', usedOn: [...PLP3, 'brand', 'search-results'],
    source: 'plp.js',
    variants: [v('Default', 'plp', '#plpPaginationDesktop', { selM: '#plpPaginationMobile' })] },
  { id: 'video-carousel', group: 'listing', name: 'Video Carousel', build: 'shared', usedOn: PLP3,
    source: 'plp.js',
    variants: [v('Default', 'plp', '.plp-video-carousel-section')] },
  { id: 'vehicle-chip', group: 'listing', name: 'Vehicle Chip (filter by vehicle)', build: 'shared', usedOn: ['brand'],
    source: 'plpRenderVehicleChip (plp.js)',
    note: 'Only shown once a vehicle is set.',
    variants: [v('Vehicle set', 'brand', '.plp-vehicle-chip')] },
  { id: 'search-headline', group: 'listing', name: 'Search Headline + Scope Buttons', build: 'shared', usedOn: ['search-results'],
    source: 'plp.js',
    variants: [v('"roof rack"', 'search-results', '.plp-search-headline'), v('Zero results — "snorkel"', 'search-results', 'main', { q: 'q=snorkel' })] },
  { id: 'search-vehicle-strip', group: 'listing', name: 'Search Vehicle Strip', build: 'shared', usedOn: ['search-results'],
    source: 'plp.js',
    variants: [v('Fits', 'search-results', '.plp-search-vehicle-strip'), v('Another vehicle\'s products — "ranger"', 'search-results', '.plp-search-vehicle-strip', { q: 'q=ranger' })] },
  { id: 'fitment-gallery', group: 'listing', name: 'Fitment Gallery', build: 'shared', usedOn: ['home', 'vehicle-specific', 'vehicle-category-landing', 'vlp', 'vplp', 'brand'],
    source: 'fitGalleryPanelHTML / mountFitGallery (shared.js); plpFitGallerySectionHTML (plp.js)',
    note: 'Hidden when a vehicle has no customer fitment photos.',
    variants: [
      v('Vehicle-Specific', 'vehicle-specific', '.fit-gallery-section'),
      v('VCLP', 'vehicle-category-landing', '.fit-gallery-section'),
      v('Home', 'home', '.fit-gallery-section'),
    ] },
  { id: 'fitment-gallery-slideout', group: 'listing', name: 'Fitment Gallery Slide-out', build: 'shared', usedOn: ['home', 'vehicle-specific', 'vehicle-category-landing', 'vlp', 'vplp', 'brand'],
    source: 'buildFitGallerySlideout (shared.js)',
    variants: [v('Open', 'vehicle-category-landing', '.fit-gallery-slideout-backdrop', { do: 'call:openFitGallerySlideout', h: 780 })] },
  { id: 'product-carousel', group: 'listing', name: 'Product Carousel', build: 'mixed', usedOn: ['home', 'store', 'cart', 'vlp', 'brand'],
    source: 'Static shell per page; initProductCarousels (shared.js), cards from plpCardHTML',
    variants: [v('Home', 'home', '.product-carousel-section'), v('Cart — also bought', 'cart', '.product-carousel-section', { cart: 'full' }), v('Brand', 'brand', '.product-carousel-section')] },
  { id: 'category-tiles', group: 'listing', name: 'Category Tiles', build: 'copied', usedOn: ['home', 'installation', 'cart', 'vlp', 'brand'],
    source: 'Inline per page — no shared function (home, installation, cart, brand, vlpTileHTML)',
    variants: [
      v('Home — Shop by Category', 'home', '#shop-by-category'),
      v('VLP — vehicle categories', 'vlp', '#vlpSectionMain'),
      v('VLP — adventure band', 'vlp', '#vlpSectionAdventure'),
      v('Brand', 'brand', '#brandTilesSection'),
      v('Installation', 'installation', '#installFitGrid'),
      v('Empty cart', 'cart', '#cartCategories'),
    ] },
  { id: 'category-tile', group: 'listing', name: 'Category Tile — every size', build: 'copied', usedOn: ['home', 'installation', 'cart', 'vlp', 'brand'],
    source: 'Inline per page — .cat-tile--feature / --standard / --compact / --product / --ask (shared.css)',
    variants: [
      v('Feature', 'vlp', '.cat-tile--feature'),
      v('Standard', 'vlp', '.cat-tile--standard'),
      v('Compact', 'vlp', '.cat-tile--compact'),
      v('Product', 'brand', '.cat-tile--product'),
      v('Ask us', 'installation', '.cat-tile--ask'),
    ] },
  { id: 'store-finder-tile', group: 'listing', name: 'Store Finder Tile', build: 'copied', usedOn: ['home', 'vlp'],
    source: 'Static + map; vlpSizeStoreFinder (vlp)',
    variants: [v('Home', 'home', '.store-finder-tile'), v('VLP', 'vlp', '.store-finder-tile')] },
  { id: 'vehicle-notice', group: 'listing', name: 'Vehicle Notice', build: 'shared', usedOn: ['vlp', 'search-results'],
    source: 'plp.js',
    variants: [v('VLP — session vehicle differs', 'vlp', '[class*="vehicle-notice"]', { ls: S.ranger })] },

  // ---------------------------------------------------------------- Cart & checkout
  { id: 'cart-line', group: 'cart', name: 'Cart Line', build: 'shared', usedOn: ['cart', 'checkout', 'order-confirmation'],
    source: 'rrgCartLineHTML (cart.js)',
    variants: [
      v('Cart (editable)', 'cart', '#cartLines', { cart: 'full' }),
      v('Checkout summary (compact)', 'checkout', '#coSummary', { selM: '#coSummaryMobile', do: 'click:#coSummaryMobile summary', cart: 'full' }),
    ] },
  { id: 'cart-summary', group: 'cart', name: 'Cart Summary (Collect / Delivery, totals, express pay)', build: 'copied', usedOn: ['cart'],
    source: 'Inline in cart; rrgBnplHTML (cart.js)',
    variants: [
      v('AU', 'cart', '.cart-summary', { cart: 'full' }),
      v('NZ', 'cart', '.cart-summary', { cart: 'full', ls: S.nz }),
      v('UK', 'cart', '.cart-summary', { cart: 'full', ls: S.uk }),
      v('Sale on (Rack Friday)', 'cart', '.cart-summary', { cart: 'full', ls: S.sale }),
    ] },
  { id: 'cart-empty', group: 'cart', name: 'Empty Cart', build: 'copied', usedOn: ['cart'],
    source: 'Inline in cart',
    variants: [v('Vehicle set', 'cart', '#cartEmpty'), v('No vehicle', 'cart', '#cartEmpty', { ls: S.noVehicle })] },
  { id: 'checkout-shell', group: 'cart', name: 'Checkout Header & Footer', build: 'copied', usedOn: ['checkout'],
    source: 'Static in checkout',
    variants: [v('Header', 'checkout', '.checkout-header', { cart: 'full' }), v('Footer', 'checkout', '.checkout-footer', { cart: 'full' })] },
  { id: 'checkout-steps', group: 'cart', name: 'Checkout Steps', build: 'copied', usedOn: ['checkout'],
    source: 'Static in checkout',
    variants: [v('Step 1', 'checkout', '.checkout-steps', { cart: 'full' })] },
  { id: 'checkout-details', group: 'cart', name: 'Checkout — Details & Delivery', build: 'copied', usedOn: ['checkout'],
    source: 'Inline in checkout',
    variants: [
      v('Logged in', 'checkout', '#stepShipping', { cart: 'full' }),
      v('Guest', 'checkout', '#stepShipping', { cart: 'full', ls: S.guest }),
      v('UK', 'checkout', '#stepShipping', { cart: 'full', ls: S.uk }),
    ] },
  { id: 'order-summary', group: 'cart', name: 'Order Summary Panel', build: 'copied', usedOn: ['checkout', 'order-confirmation'],
    source: 'Inline in checkout and order-confirmation',
    variants: [v('Checkout', 'checkout', '.checkout-summary', { selM: '#coSummaryMobile', do: 'click:#coSummaryMobile summary', cart: 'full' }), v('Confirmation', 'order-confirmation', '.checkout-summary', { order: 'collect' })] },
  { id: 'confirmation-hero', group: 'cart', name: 'Order Confirmation Hero', build: 'copied', usedOn: ['order-confirmation'],
    source: 'Inline in order-confirmation',
    variants: [v('Click & Collect', 'order-confirmation', '.confirm-hero', { order: 'collect' }), v('Delivery', 'order-confirmation', '.confirm-hero', { order: 'delivery' })] },
  { id: 'confirmation-next', group: 'cart', name: 'What Happens Next', build: 'copied', usedOn: ['order-confirmation'],
    source: 'Inline in order-confirmation',
    variants: [v('Click & Collect', 'order-confirmation', '.confirm-main-col .co-section', { order: 'collect' }), v('Delivery', 'order-confirmation', '.confirm-main-col .co-section', { order: 'delivery' })] },
  { id: 'book-fitting', group: 'cart', name: 'Book a Fitting Card', build: 'copied', usedOn: ['order-confirmation'],
    source: 'Inline in order-confirmation',
    variants: [v('Default', 'order-confirmation', '#confirmFitting', { order: 'collect' })] },

  // ---------------------------------------------------------------- Stores, vehicles & brands
  { id: 'vehicle-finder', group: 'stores', name: 'Vehicle Finder (inline)', build: 'shared', usedOn: ['home', 'fit-my-vehicle', 'cart', 'vehicle-category-landing', 'brand'],
    source: 'rrgWidgetVehicleFinderHTML (widgets.js); initInlineFitFinders / initVehicleFinder (shared.js). Also inside the Fit Finder Drawer',
    variants: [
      v('Vehicle known — light', 'fit-my-vehicle', '.fit-finder-widget'),
      v('Vehicle known — dark', 'fit-my-vehicle', '.fit-finder-widget', { ls: S.dark }),
      v('No vehicle — light', 'fit-my-vehicle', '.fit-finder-widget', { ls: S.noVehicle }),
      v('No vehicle — dark', 'fit-my-vehicle', '.fit-finder-widget', { ls: { ...S.noVehicle, ...S.dark } }),
      v('Home (above the hero)', 'home', '.home-finder'),
      v('VCLP (Toyota / Hilux pre-filled)', 'vehicle-category-landing', '#fitFinder', { ls: S.noVehicle }),
      v('Brand page', 'brand', '#brandFinder'),
    ] },
  { id: 'store-card', group: 'stores', name: 'Store Card', build: 'copied', usedOn: ['store-finder', 'installation', 'order-confirmation', 'checkout'],
    source: 'Inline, duplicated: sfCardHTML (store-finder), installation, storeCardHTML (order-confirmation, checkout)',
    variants: [
      v('Store Finder', 'store-finder', '.sf-card'),
      v('Store Finder — UK coming soon', 'store-finder', '.sf-card', { ls: S.uk, nth: 1 }),
      v('Installation', 'installation', '.sf-card'),
      v('Order confirmation', 'order-confirmation', '.confirm-store-card', { order: 'collect' }),
    ] },
  { id: 'store-panel', group: 'stores', name: 'Store Panel (store page)', build: 'copied', usedOn: ['store'],
    source: 'Inline in store, from stores-data.js',
    variants: [v('North Lakes', 'store', '.store-panel'), v('Moorebank', 'store', '.store-panel', { q: 'store=moorebank' }), v('Not your store', 'store', '.store-panel', { ls: S.noStore })] },
  { id: 'store-reviews', group: 'stores', name: 'Store Reviews Row', build: 'copied', usedOn: ['store'],
    source: 'Inline in store',
    variants: [v('Default', 'store', '#storeReviews')] },
  { id: 'store-local', group: 'stores', name: 'Store Local Copy + Map', build: 'copied', usedOn: ['store'],
    source: 'Inline in store',
    variants: [v('Default', 'store', '.store-local')] },
  { id: 'store-finder-search', group: 'stores', name: 'Store Finder Search', build: 'copied', usedOn: ['store-finder'],
    source: 'Static in store-finder',
    variants: [v('Default', 'store-finder', '.sf-search')] },
  { id: 'store-finder-layout', group: 'stores', name: 'Store Finder — State Tabs, List + Map', build: 'copied', usedOn: ['store-finder'],
    source: 'Inline in store-finder',
    variants: [v('AU', 'store-finder', '#sfLayout', { sizes: ['d'] }), v('State tabs', 'store-finder', '#sfTabs'), v('NZ', 'store-finder', '#sfLayout', { ls: S.nz, sizes: ['d'] })] },
  { id: 'booking-form', group: 'stores', name: 'Installation Booking Form', build: 'copied', usedOn: ['installation'],
    source: 'Inline in installation',
    variants: [v('Default', 'installation', '#book')] },
  { id: 'price-accordion', group: 'stores', name: 'Fitting Charges List', build: 'copied', usedOn: ['installation'],
    source: 'Static in installation',
    variants: [v('Default', 'installation', '#costs')] },
  { id: 'roof-types', group: 'stores', name: 'Roof Types', build: 'copied', usedOn: ['fit-my-vehicle'],
    source: 'Static in fit-my-vehicle',
    variants: [v('Default', 'fit-my-vehicle', '.roof-types')] },
  { id: 'load-panels', group: 'stores', name: 'Load Ratings', build: 'copied', usedOn: ['fit-my-vehicle'],
    source: 'Static in fit-my-vehicle',
    variants: [v('Default', 'fit-my-vehicle', '.load-panels')] },
  { id: 'info-cards', group: 'stores', name: 'Info Cards', build: 'copied', usedOn: ['fit-my-vehicle'],
    source: 'Static in fit-my-vehicle',
    variants: [v('4-up', 'fit-my-vehicle', '.info-cards--4'), v('Default', 'fit-my-vehicle', '.info-cards:not(.info-cards--4)')] },
  { id: 'generation-table', group: 'stores', name: 'Vehicle Generation Table', build: 'copied', usedOn: ['vehicle-category-landing'],
    source: 'Static in vehicle-category-landing',
    variants: [v('Default', 'vehicle-category-landing', '.vclp-gen-table')] },
  { id: 'brand-banner', group: 'stores', name: 'Brand Banner', build: 'copied', usedOn: ['brand'],
    source: 'Inline renderBrandHero (brand)',
    variants: ['thule', 'rhino-rack', 'front-runner'].map(b => v(b.replace('-', ' ').replace(/\b\w/g, c => c.toUpperCase()), 'brand', '#brandHero', { q: 'brand=' + b })) },
  { id: 'brand-about', group: 'stores', name: 'Brand About Band', build: 'copied', usedOn: ['brand'],
    source: 'Inline renderBrandAbout (brand)',
    variants: ['thule', 'rhino-rack'].map(b => v(b === 'thule' ? 'Thule' : 'Rhino Rack', 'brand', '#brandAbout', { q: 'brand=' + b })) },
  { id: 'brand-cards', group: 'stores', name: 'Brand Cards (Brands hub)', build: 'copied', usedOn: ['brands'],
    source: 'Inline in brands',
    variants: [v('Grid', 'brands', '#brandCardGrid'), v('A–Z list', 'brands', '#allBrands')] },

  // ---------------------------------------------------------------- Home & content blocks
  { id: 'home-hero', group: 'content', name: 'Home Hero Slider', build: 'mixed', usedOn: ['home'],
    source: 'Static; initHomeHero (shared.js)',
    variants: [v('Vehicle known', 'home', '.home-hero'), v('No vehicle', 'home', '.home-hero', { ls: S.noVehicle }), v('Sale on — Rack Friday slide first', 'home', '.home-hero', { ls: S.sale })] },
  { id: 'offer-tiles', group: 'content', name: 'Promo Row (Category Tiles + Offers Carousel)', build: 'mixed', usedOn: ['home'],
    source: 'Static; initOfferCarousel (shared.js)',
    variants: [v('Default', 'home', '.home-promo-row')] },
  { id: 'reviews-row', group: 'content', name: 'Customer Reviews Row', build: 'copied', usedOn: ['home', 'store'],
    source: 'Static per page',
    variants: [v('Home', 'home', '.home-reviews'), v('Store', 'store', '#storeReviews')] },
  { id: 'help-row', group: 'content', name: 'Help Row', build: 'copied', usedOn: ['home'],
    source: 'Static in home',
    variants: [v('Default', 'home', '.home-help-grid')] },
  { id: 'trust-row', group: 'content', name: 'Trust Row', build: 'copied', usedOn: ['home', 'store', 'fit-my-vehicle', 'installation', ...PDP5],
    source: 'Static per page — the copy differs on every page (REGION_TRUST_COPY)',
    variants: [
      v('Product page', 'simple', '.trust-row'),
      v('Home', 'home', '.trust-row'),
      v('Store (services)', 'store', '.trust-row'),
      v('Fit My Vehicle', 'fit-my-vehicle', '.trust-row'),
      v('Installation', 'installation', '.trust-row'),
      v('UK', 'simple', '.trust-row', { ls: S.uk }),
    ] },
  { id: 'trust-banner', group: 'content', name: 'Trust Banner (install photo)', build: 'copied', usedOn: ['home', 'store-finder', 'vehicle-category-landing', 'vlp', 'brand', 'brands'],
    source: 'Static per page — the copy differs per page',
    variants: [v('Home', 'home', '.vclp-trust-banner'), v('VCLP', 'vehicle-category-landing', '.vclp-trust-banner'), v('Store Finder', 'store-finder', '.vclp-trust-banner'), v('Brands hub', 'brands', '.vclp-trust-banner')] },
  { id: 'brands-strip', group: 'content', name: 'Shop The Best Brands', build: 'copied', usedOn: ['home', 'store', 'store-finder', 'fit-my-vehicle', 'installation', 'cart', 'order-confirmation', 'vehicle-category-landing', 'vlp', 'brand'],
    source: 'Static, identical on 8 pages; VCLP differs; brand page uses renderOtherBrands',
    variants: [v('Home', 'home', '.brands-section'), v('VCLP', 'vehicle-category-landing', '.brands-section'), v('Brand page (other brands)', 'brand', '.brands-section')] },
  { id: 'faq', group: 'content', name: 'FAQ', build: 'mixed', usedOn: ['store', 'fit-my-vehicle', 'installation', ...PDP5, 'vehicle-category-landing', 'vlp', ...PLP3, 'brand'],
    source: 'Static on PDPs + VCLP; plpRenderFAQ (plp.js); vlpRenderFaq, renderBrandFaq inline',
    variants: [v('Product page', 'simple', '.faq-section'), v('PLP', 'plp', '.faq-section'), v('VCLP', 'vehicle-category-landing', '.faq-section'), v('Brand', 'brand', '.faq-section'), v('Fit My Vehicle', 'fit-my-vehicle', '.faq-section')] },
  { id: 'page-hero', group: 'content', name: 'Page Hero', build: 'copied', usedOn: ['fit-my-vehicle', 'installation'],
    source: 'Static per page',
    variants: [v('Fit My Vehicle', 'fit-my-vehicle', '.page-hero'), v('Installation', 'installation', '.page-hero')] },
  { id: 'content-block', group: 'content', name: 'Content Block / Split Media', build: 'copied', usedOn: ['store', 'fit-my-vehicle', 'vehicle-category-landing'],
    source: 'Static per page',
    variants: [v('VCLP', 'vehicle-category-landing', '.content-block'), v('Fit My Vehicle (split media)', 'fit-my-vehicle', '.split-media')] },
  { id: 'steps', group: 'content', name: 'Steps', build: 'copied', usedOn: ['fit-my-vehicle', 'installation'],
    source: 'Static per page',
    variants: [v('With photos', 'fit-my-vehicle', '.steps--photos'), v('Installation', 'installation', '.steps')] },
  { id: 'callout', group: 'content', name: 'Callout', build: 'copied', usedOn: ['fit-my-vehicle', 'installation'],
    source: 'Static per page',
    variants: [v('Fit My Vehicle', 'fit-my-vehicle', '.callout'), v('Installation', 'installation', '.callout')] },

  // ---------------------------------------------------------------- Building blocks (drawn on the library page itself)
  { id: 'colours', group: 'blocks', name: 'Colours', build: 'shared', usedOn: ALL_PAGES, source: ':root tokens (shared.css)', local: 'colours' },
  { id: 'typography', group: 'blocks', name: 'Typography', build: 'shared', usedOn: ALL_PAGES, source: 'h1–h4, body (shared.css)', local: 'typography' },
  { id: 'buttons', group: 'blocks', name: 'Buttons', build: 'shared', usedOn: ALL_PAGES, source: '.btn-* (shared.css)', local: 'buttons' },
  { id: 'chips', group: 'blocks', name: 'Chips & Stock Pills', build: 'shared', usedOn: [...PDP5, 'home', 'vlp'], source: '.chip, .stock-chip (shared.css)', local: 'chips' },
  { id: 'form-fields', group: 'blocks', name: 'Form Fields', build: 'shared', usedOn: ['checkout', 'installation', 'store-finder', 'order-confirmation'], source: 'inputs, selects (shared.css)', local: 'forms' },
];
